
spring:
#配置数据库spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dbForSSM?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: pyb
server:
  port: 8081

