
spring:
#配置数据库spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: pyb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081

